import "./globals.css";
import Header from "@/components/header/header";
import { Providers } from "./providers";
import { Poppins } from "next/font/google";
import Footer from "@/components/footer/footer";
import ReactQueryProvider from "@/wrapper/queryClientWrapper";
import { ToastContainer } from "@/services/toastmessage";
const poppins = Poppins({
  subsets: [ "latin" ],
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900" ],
  display: "swap",
});

export const metadata = {
  title: "Innovators",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ReactQueryProvider>
          <ToastContainer />
          <Providers>
            <Header className="" />
            <main>{children}</main>
            <Footer />
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
